// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrendModelService.Server.Models;

namespace TrendModelService.Server.Migrations
{
    [DbContext(typeof(TrendContext))]
    [Migration("20200924172759_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("TrendModelService.Shared.Trend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AspectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendTrace")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendTreatment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trends");
                });
#pragma warning restore 612, 618
        }
    }
}
